server:
  port: 8010
#当前服务注册在eureka service上的名称
spring:
  application:
    name: provider2
#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#是否将当前服务的ip注册到eureka service
  instance:
    prefer-ip-address: true